name: Gradle Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v4.2.2
      - name: Set up JDK 17
        uses: actions/setup-java@v3.0.0
        with:
          java-version: 17
          distribution: liberica

      - name: Gradle Wrapper Validation
        uses: gradle/wrapper-validation-action@v1.0.4
      - uses: gradle/gradle-build-action@v2.1.5
        with:
          arguments: build --stacktrace
      - name: Upload Test Report
        uses: actions/upload-artifact@v4
        if: ${{ always() }}
        with:
          name: test-report
          path: |
            build/reports/tests/**/*